### ISSUE TITLE
GitHubActionsでのエラー

### ISSUE THREAD

**Issue by daikimatsumoto0731** [daikimatsumoto0731/vegetable_service#109]
エラー画面
[![Image from Gyazo](https://i.gyazo.com/771e2063a3ec16b5220e355fe199cc43.png)](https://gyazo.com/771e2063a3ec16b5220e355fe199cc43)

該当するテストコード
https://github.com/daikimatsumoto0731/vegetable_service/blob/main/spec/system/analyze_image_spec.rb

エラーの概要
ローカルではテストは全て通ってるがGitHub Actionでは通らなかった。
原因は環境変数 GOOGLE_APPLICATION_CREDENTIALS が正しく設定されていない可能性がある。

対策として.github/workflow/ci.ymlを作った。
コードはhttps://github.com/daikimatsumoto0731/vegetable_service/blob/main/.github/workflows/ci.yml

GitHub Secretsの設定をした。
Settings > Secrets > Actions に進み、新しいシークレットを追加。

結果としてエラーが解消されなかった。

他に必要なファイルがあれば教えてください

**Comment by Tsuchiya2** [comment]
エラー内容からおそらく画像投稿が上手くいっていない状態かと思うので、テスト実行時にアップロードする画像が存在するかどうかの確認（GitHubActions）、もしくは画像分析のテストはリクエストスペックに変更して、モックを作ってそちらでテスト通過する形にできないかを試すなどしてみてください。

（モックやリクエストスペックなど、分からないことは調べてみてください。）
